blank_issues_enabled: false
# contact_links:
#   - name: Use DNSTools
#     url: https://lewiswigmore.github.io/dns-tools/
#     about: Try the live web UI application
#   - name: General DNS Questions
#     url: https://stackoverflow.com/questions/tagged/dns
#     about: For general DNS questions, Stack Overflow might be helpful