name: Feature Request
description: Suggest a new feature or improvement for DNS Tools
title: "[Feature] "
labels: ["enhancement"]
assignees:
  - lewiswigmore
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please provide as much detail as possible.

  - type: textarea
    id: feature-description
    attributes:
      label: Feature Description
      description: Describe the feature you'd like to see
      placeholder: A clear and concise description of what you want to happen
    validations:
      required: true

  - type: textarea
    id: problem-solution
    attributes:
      label: Problem This Solves
      description: What problem does this feature solve?
      placeholder: Explain the use case or problem this feature would address
    validations:
      required: true

  - type: dropdown
    id: feature-area
    attributes:
      label: Feature Area
      description: Which part of the application would this feature affect?
      options:
        - DNS Lookup
        - MX Lookup
        - DMARC Lookup
        - Email Headers
        - History
        - Dashboard
        - Resources
        - User Interface
        - New Tool/Feature
        - Performance
        - Other
    validations:
      required: true

  - type: textarea
    id: proposed-solution
    attributes:
      label: Proposed Solution
      description: How do you think this feature should work?
      placeholder: Describe your proposed implementation or behavior

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternative solutions?
      placeholder: What other approaches might work?

  - type: dropdown
    id: priority
    attributes:
      label: Priority Level
      description: How important is this feature to you?
      options:
        - Low - Nice to have
        - Medium - Would improve my workflow
        - High - Essential for my use case
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context or screenshots about the feature request
      placeholder: Mockups, examples, related tools, etc.