name: Question
description: Ask a question about DNS Tools or DNS concepts
title: "[Question] "
labels: ["question"]
assignees:
  - lewiswigmore
body:
  - type: markdown
    attributes:
      value: |
        Have a question about DNS Tools or need help with DNS concepts? We're here to help!

  - type: textarea
    id: question
    attributes:
      label: Your Question
      description: What would you like to know?
      placeholder: Ask your question here
    validations:
      required: true

  - type: dropdown
    id: question-type
    attributes:
      label: Question Type
      description: What kind of question is this?
      options:
        - How to use DNS Tools
        - DNS concept explanation
        - Troubleshooting help
        - Record interpretation
        - Email security (DMARC/SPF/DKIM)
        - General DNS knowledge
        - Other
    validations:
      required: true

  - type: input
    id: domain-example
    attributes:
      label: Domain Example (Optional)
      description: If your question relates to a specific domain, you can share it here
      placeholder: e.g., example.com

  - type: textarea
    id: what-tried
    attributes:
      label: What Have You Tried?
      description: If you're troubleshooting, what have you already attempted?
      placeholder: Describe any steps you've already taken

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Any other information that might be helpful
      placeholder: Screenshots, error messages, specific use case, etc.